### ISSUE TITLE
401 Unauthorized @ redmine-1.0.1

### ISSUE THREAD

**Issue by anibalsanchez** [fernandokosh/redmine_time_tracker#24]
TimeTrackersController#render_menu is trying to access 
http://.................../time_trackers/render_menu.... even when the user is not logged in.

So we are getting a login dialog for Redmine API.....
Processing TimeTrackersController#render_menu (for 216.18.209.146 at 2010-09-02 15:20:05) [POST]
  Parameters: {"action"=>"render_menu", "authenticity_token"=>"9yQj....................MY=", "controller"=>"time_trackers"}
Filter chain halted as [:check_if_login_required] rendered_or_redirected.
Completed in 3ms (View: 0, DB: 0) | 401 Unauthorized [http://....../time_trackers/render_menu]

Which is the way to fix it ?

PD: GREAT PLUGIN !!!!!

Thanks,
Anibal

**Comment by delaitre** [comment]
This seems similar to issue #4 which is fixed in master. Tell me if this is not the case.

**Comment by anibalsanchez** [comment]
We''ve installed the latest version. delaitre-redmine_time_tracker-0.2.0-0-g0798f13.zip

It's not fixed.

It's trying to access an internal page, when the user is not logged in.

Please, let me know if there's a way to disble the polling.

You can check it here http://project.nextperience.net. Wait 10 secs.

Thanks,
Anibal

**Comment by delaitre** [comment]
I know this is not fixed in 0.2.0. You have to take the current development version (which I strongly recommend as it fixed a lot of bug). However, if you just want to fix this bug, you can look at SHA: 822b573601875c618d87964589d655e670a674eb

**Comment by anibalsanchez** [comment]
We've implemented the fix, restarted the service... and It's not fixing the issue. 

I see several changes... It may be better to deploy the full dev package.... or wait for the next release.

Thanks,
Anibal

**Comment by delaitre** [comment]
I don't know when I will made the next release. Indeed the current dev package could be the next release... Most of users use it already without problems.

At least, it would be useful to test this bug with the dev package to see if it is already corrected or not. I just tried on a fresh redmine 1.0.1 and I have no problem with the dev package.

**Comment by delaitre** [comment]
Well, looking at the current state of the code and the issue list, I think I'll make a new release. However, I'll greatly appreciate a feedback on this issue before releasing.

**Comment by anibalsanchez** [comment]
I'm going to test it... within a week 

Txs
Anibal

**Comment by anibalsanchez** [comment]
Hi delaitre,

It works Ok. As a minor tweak, we've fixed the spanish translation (From "time_tracker_admin_menu" to "time_tracker_settings_zombie_transition" are not translated).

Thanks
Anibal

**Comment by delaitre** [comment]
Thanks for testing this. Could you send me your updated spanish translation to include it to the next release?
